ruleset:
  # Örnek kurallar
  maxLineLength: 120 # Maksimum satır uzunluğu
  indentSize: 4      # Girinti boyutu
  noUnusedImports: true # Kullanılmayan importları kontrol et
  noBlankLinesBeforePackage: true # Paket tanımından önce boş satır olmasın